=== manjangoc/WS17-18_CPP/Vorbereitung 1/medi.dtd
<!ELEMENT Mediathek (infos+)>
          <!ELEMENT infos (titel, jahr, produktionsland, laenge, regie, cast)>
          <!ATTLIST infos
          id ID #REQUIRED>
          <!ELEMENT titel (#PCDATA)>
          <!ELEMENT jahr (#PCDATA)>
          <!ELEMENT produktionsland (#PCDATA)>
          <!ELEMENT laenge (#PCDATA)>
          <!ELEMENT regie (#PCDATA)>
          <!ELEMENT cast (#PCDATA)>

=== manjangoc/WS17-18_CPP/mediathek.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mediathek SYSTEM "medi.dtd">
<Mediathek>
 <film>
     <infos id="eins">
         <titel>Like Crazy</titel>
         <jahr>2011</jahr>
         <produktionsland>USA</produktionsland>
         <laenge>86 min</laenge>
         <regie>Drake Doremus</regie>
         <cast>Anton Yelchin</cast>
     </infos>
     <infos id="zwei">
         <titel>10 Things I Hate About You</titel>
         <jahr>1999</jahr>
         <produktionsland>USA</produktionsland>
         <laenge>97 min</laenge>
         <regie>Gil Junger</regie>
         <cast>Julia Stiles</cast>
     </infos>
     <infos id="drei">
         <titel>Submarine</titel>
         <jahr>2010</jahr>
         <produktionsland>USA, UK</produktionsland>
         <laenge>97 min</laenge>
         <regie>Richard Ayoade</regie>
         <cast>Craig Roberts</cast>
     </infos>
     <infos id="vier">
         <titel>Victoria</titel>
         <jahr>2015</jahr>
         <produktionsland>Deutschland</produktionsland>
         <laenge>140 min</laenge>
         <regie>Sebastian Schipper</regie>
         <cast>Laia Costa</cast>
     </infos>
     <infos id="fÃ¼nf">
         <titel>Breakfast at Tiffany's</titel>
         <jahr>1961</jahr>
         <produktionsland>USA</produktionsland>
         <laenge>110 min</laenge>
         <regie>Blake Edwards</regie>
         <cast>Audrey Hepburn</cast>
     </infos>
 </film>
</Mediathek>
